- name: update and upgrade apt packages
  ansible.builtin.apt:
   update_cache: yes
   upgrade: dist
  become: yes

- name: Update cache
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: install  python3-apt 
  ansible.builtin.yum:
   name: python3-apt
   state: present


- name: Install redis repo
  ansible.builtin.yum:
    name: "redis"
    state: present

- name: allow remote connections to redis
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start and enable redis
  ansible.builtin.service:
    name: redis
    state: started
    enabled: yes
