# Refer nodejs task in common folder
# catalogue is 1 role and common is another role
# need to import a task nodejs.yaml in catalogue



- name: Install nodejs
  ansible.builtin.import_roles:
   name: common
   task_from: nodejs