- name: Install nodejs
  ansible.builtin.import_role:
   name: common
   tasks_from: nodejs


- name: Ensure /app directory exists
  ansible.builtin.file:
    path: /app
    state: directory
    

# --- Your existing tasks below this line ---
- name: Copy or extract application files
  ansible.builtin.copy:  # Or unarchive, template, etc.
    src: your_source_files
    dest: /app



- name: setup application
  ansible.builtin.import_role:
   name: common
   tasks_from: app-setup

- name: install dependencies
  ansible.builtin.command: npm install
  args: 
   chdir: /app



- name: load schema
  ansible.builtin.import_role:
   name: common
   tasks_from: load-mongo-schema.yaml




- name: reload systemd demon
  ansible.builtin.import_role:
   name: common
   tasks_from: systemd-setup.yaml
