- name: copy mongoDB repo file
  ansible.builtin.copy:
   src: mongodb.repos
   dest: /etc/yum.repos.d/mongodb-org-8.0.repo

- name: Install MongoDB
  ansible.builtin.yum:
   name: mongodb-org
   state: installed

- name: Install MongoDB Shell client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

- name: load {{ component }} data
  ansible.builtin.command: mongosh --host 172.31.30.150 </app/schema/{{ component }}.js


